// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
}
export {}
